/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "ChannelsImpl.h"
#include "TwilioIPMessagingClientContextDefines.h"
#include "ITMChannel.h"

#include <twilio-jni/twilio-jni.h>
#include <android/log.h>

using namespace rtd;

#define TAG  "ChannelsImpl(native)"
/*
 * Class:     com_twilio_ipmessaging_impl_ChannelsImpl
 * Method:    createChannelNative
 * Signature: (Ljava/lang/String;Lcom/twilio/ipmessaging/ChannelListener;)Lcom/twilio/ipmessaging/Message;
 */
JNIEXPORT jobject JNICALL Java_com_twilio_ipmessaging_impl_ChannelsImpl_createChannelNative
  (JNIEnv *env, jobject obj, jstring friendlyName, jobject listener) {

	jobject channel;
	jlong nativeChannelsContext = tw_jni_fetch_long(env, obj, "nativeChannelsHandler");
//	LOG_D(TAG,"createChannelNative : Checking nativeChannelsContext.");
	if (nativeChannelsContext == 0) {
//		LOG_W(TAG,"nativeChannelsContext is null");
		return nullptr;
	} else {
		ChannelsContext *channelsContextRecreate = reinterpret_cast<ChannelsContext *>(nativeChannelsContext);
//		LOG_D(TAG,"client context is recreated.");

		if(channelsContextRecreate == nullptr) {
	//		LOG_W(TAG,"channelsContextRecreate is NULL.");
			return 0;
		}

		if(channelsContextRecreate->channels == nullptr) {
	//		LOG_W(TAG, "createChannelNative : ITChannelsPtr is NULL.");
			return 0;
		}

		ITMChannelsPtr channelsPtr = channelsContextRecreate->channels;

		if (channelsPtr != nullptr) {
			const char *nativeNameString = env->GetStringUTFChars(friendlyName, JNI_FALSE);
			ITMChannelPtr channelPtr = channelsPtr->createChannel();
	//		LOG_D(TAG, "createChannelNative : created channel setting type.");
			channelPtr->setType(rtd::kTMChannelTypePublic, [](TMResult result) {});
	//		LOG_D(TAG,"createChannelNative : setting type.");
			channelPtr->setName(nativeNameString, NULL);
	//		LOG_D( TAG,"createChannelNative : Setting name.");
			channelsPtr->add(channelPtr, nullptr);
	//		LOG_D(TAG, "createChannelNative: channel added.");

			//Create channel context
			ChannelContext* channelContext_ = new ChannelContext();
			channelContext_->channel = channelPtr;
			jlong channelContextHandle = reinterpret_cast<jlong>(channelContext_);

			const char* sid = channelPtr->getSid().c_str();
			const char* name = channelPtr->getName().c_str();

		//	LOGW("Channel Name  : %s.", name );
		//	LOGW("Channel Sid %s", sid);


			jstring nameString = env->NewStringUTF(name);
			jstring sidString = env->NewStringUTF(sid);

			//create channel object
			jclass java_channel_impl_cls = tw_jni_find_class(env, "com/twilio/ipmessaging/impl/ChannelImpl");
			if(java_channel_impl_cls != nullptr) {
				//LOG_D(TAG, "Found java_channel_impl_cls class" );
			}

			jmethodID construct = tw_jni_get_method_by_class(env, java_channel_impl_cls, "<init>", "(Ljava/lang/String;Ljava/lang/String;J)V");
			channel = tw_jni_new_object(env, java_channel_impl_cls, construct, nameString, sidString, channelContextHandle);
			//LOG_D(TAG, "Created Channel Object.");

			jmethodID method = tw_jni_get_method_by_class(env, java_channel_impl_cls, "setListener", "(Lcom/twilio/ipmessaging/ChannelListener;)V");
			//LOG_D(TAG, "Setting channel listener.");

			env->CallVoidMethod(channel, method, listener);

			//Cleanup
			//LOG_D(TAG,"createChannelNative: release native string.");
			env->ReleaseStringUTFChars(friendlyName, nativeNameString);


		} else {
			//LOG_E(TAG, "channels is null");
		}
	}

	return channel;
}

/*
 * Class:     com_twilio_ipmessaging_impl_ChannelsImpl
 * Method:    getChannelNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT jobject JNICALL Java_com_twilio_ipmessaging_impl_ChannelsImpl_getChannelNative
  (JNIEnv *env, jobject obj, jstring channel_sid) {

	jobject channel;
	jlong nativeChannelsContext = tw_jni_fetch_long(env, obj, "nativeChannelsHandler");

	if(channel_sid != nullptr) {
		const char *nativeString = env->GetStringUTFChars(channel_sid, JNI_FALSE);

		//LOG_D( TAG, "createChannelNative : Checking nativeChannelsContext.");

		if (nativeChannelsContext == 0) {
			//LOGW("nativeChannelsContext is null");
			return nullptr;
		} else {

			ChannelsContext *channelsContextRecreate = reinterpret_cast<ChannelsContext *>(nativeChannelsContext);
			//LOG_D(TAG, "client context is recreated.");

			if(channelsContextRecreate == nullptr) {
			//	LOG_W(TAG,"createChannelNative : channelsContextRecreate is NULL.");
				return 0;
			}

			if(channelsContextRecreate->channels == nullptr) {
			//	LOG_W(TAG, "createChannelNative : ITChannelsPtr is NULL.");
				return 0;
			}

			ITMChannelsPtr channelsPtr = channelsContextRecreate->channels;
			if(channelsPtr != nullptr) {
				ITMChannelPtr channelPtr = channelsPtr->getChannel(nativeString);
				if(channelPtr != nullptr) {
					//LOG_D(TAG, "Creating channel with sid : %s ", nativeString);

					//Create channel context
					ChannelContext* channelContext_ = new ChannelContext();
					channelContext_->channel = channelPtr;
					jlong channelContextHandle = reinterpret_cast<jlong>(channelContext_);

					const char* sid = channelPtr->getSid().c_str();
					const char* name = channelPtr->getName().c_str();

					//LOG_D(TAG, "Channel Name  : %s.", name );
					//LOG_D(TAG, "Channel Sid %s", sid);

					jstring nameString = env->NewStringUTF(name);
					jstring sidString = env->NewStringUTF(sid);

					//create channel object
					jclass java_channel_impl_cls = tw_jni_find_class(env, "com/twilio/ipmessaging/impl/ChannelImpl");
					jmethodID construct = tw_jni_get_method_by_class(env, java_channel_impl_cls, "<init>", "(Ljava/lang/String;Ljava/lang/String;J)V");
					channel = tw_jni_new_object(env, java_channel_impl_cls, construct, nameString, sidString, channelContextHandle);
					//LOGD("Created Channel Object.");

				} else {
					//LOG_W(TAG, "Java_com_twilio_ipmessaging_impl_ChannelImpl_joinChannel channels is null");
				}
			}
		}
	}
	return channel;
}

/*
 * Class:     com_twilio_ipmessaging_impl_ChannelsImpl
 * Method:    getChannelsNative
 * Signature: (J)[Lcom/twilio/ipmessaging/Channel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_twilio_ipmessaging_impl_ChannelsImpl_getChannelsNative
  (JNIEnv *env, jobject obj, jlong handle) {

	jobject channel;
	jobjectArray channelsArray ;

	jlong nativeChannelsContext = tw_jni_fetch_long(env, obj, "nativeChannelsHandler");

//	LOG_D(TAG, "Checking nativeChannelsContext.");

	if (nativeChannelsContext == 0) {
		//	LOG_W(TAG, "nativeChannelsContext is null");
			return nullptr;
	} else {

		ChannelsContext *channelsContextRecreate = reinterpret_cast<ChannelsContext *>(nativeChannelsContext);
		if(channelsContextRecreate == nullptr) {
			//LOG_W(TAG, "channelsContextRecreate is null.");
			return 0;
		}

		if(channelsContextRecreate->channels == nullptr) {
			//LOG_W( TAG, " ITChannelsPtr is null.");
			return 0;
		}

		ITMChannelsPtr channels = channelsContextRecreate->channels;

		std::vector<ITMChannelPtr> channelsList;
		channels->getMyChannelsList(channelsList);

		std::vector<ITMChannelPtr> publicChannels;
		channels->getPublicChannelsList(publicChannels);

		//LOG_D(TAG,"public channels count : %d",publicChannels.size());
		//LOG_D(TAG,"my channels count : %d.", channelsList.size() );

		jclass java_channel_impl_cls = tw_jni_find_class(env, "com/twilio/ipmessaging/impl/ChannelImpl");
		jmethodID construct = tw_jni_get_method_by_class(env, java_channel_impl_cls, "<init>", "(Ljava/lang/String;Ljava/lang/String;J)V");
		channelsArray = (jobjectArray) env->NewObjectArray(publicChannels.size(),java_channel_impl_cls, 0);

		for (int i= 0; i<publicChannels.size() ; i++ ) {
			ITMChannelPtr channelPtr = publicChannels[i];
			const char* sid = channelPtr->getSid().c_str();
			const char* name = channelPtr->getName().c_str();

			ChannelContext* channelContext_ = new ChannelContext();
			channelContext_->channel = channelPtr;
			jlong channelContextHandle = reinterpret_cast<jlong>(channelContext_);
			jstring nameString = env->NewStringUTF(name);
			jstring sidString = env->NewStringUTF(sid);
			channel = tw_jni_new_object(env, java_channel_impl_cls, construct, nameString, sidString, channelContextHandle);
			env->SetObjectArrayElement(channelsArray, i, channel);
		}
	}

	return channelsArray ;

}


