/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "ChannelsImpl.h"
#include "TwilioIPMessagingClientContextDefines.h"
#include "ITMChannel.h"

#include <twilio-jni/twilio-jni.h>
#include <android/log.h>

using namespace rtd;

#define TAG  "ChannelsImpl(native)"
/*
 * Class:     com_twilio_ipmessaging_impl_ChannelsImpl
 * Method:    createChannelNative
 * Signature: (Ljava/lang/String;Lcom/twilio/ipmessaging/ChannelListener;)Lcom/twilio/ipmessaging/Message;
 */
JNIEXPORT jobject JNICALL Java_com_twilio_ipmessaging_impl_ChannelsImpl_createChannelNative
  (JNIEnv *env, jobject obj, jstring friendlyName, jobject listener, jlong nativeChannelsContext) {

	jobject channel;
	//jlong nativeChannelsContext = tw_jni_fetch_long(env, obj, "nativeChannelsHandler");
	LOGD(TAG,"createChannelNative : Checking nativeChannelsContext.");
	if (nativeChannelsContext == 0) {
		LOG_W(TAG,"nativeChannelsContext is null");
		return nullptr;
	} else {
		ChannelsContext *channelsContextRecreate = reinterpret_cast<ChannelsContext *>(nativeChannelsContext);
		LOGD(TAG,"client context is recreated.");

		if(channelsContextRecreate == nullptr) {
			LOGW(TAG,"channelsContextRecreate is NULL.");
			return 0;
		}

		if(channelsContextRecreate->channels == nullptr) {
			LOGW(TAG, "createChannelNative : ITChannelsPtr is NULL.");
			return 0;
		}

		ITMChannelsPtr channelsPtr = channelsContextRecreate->channels;

		if (channelsPtr != nullptr) {
			const char *nativeNameString = env->GetStringUTFChars(friendlyName, JNI_FALSE);
			ITMChannelPtr channelPtr = channelsPtr->createChannel();
			channelPtr->setType(rtd::kTMChannelTypePublic, [](TMResult result) {LOGD(TAG,"Channel setType command processed");});
			channelPtr->setName(nativeNameString, NULL);
			channelsPtr->add(channelPtr, [](TMResult result) {LOGD(TAG,"Channel add command processed");});

			//Create channel context
			ChannelContext* channelContext_ = new ChannelContext();
			channelContext_->channel = channelPtr;
			jlong channelContextHandle = reinterpret_cast<jlong>(channelContext_);

			const char* sid = channelPtr->getSid().c_str();
			const char* name = channelPtr->getName().c_str();

			LOGW(TAG,"Channel Name  : %s.", name );
			LOGW(TAG,"Channel Sid %s", sid);


			jstring nameString = env->NewStringUTF(name);
			jstring sidString = env->NewStringUTF(sid);

			//create channel object
			jclass java_channel_impl_cls = tw_jni_find_class(env, "com/twilio/ipmessaging/impl/ChannelImpl");
			if(java_channel_impl_cls != nullptr) {
				LOGD(TAG, "Found java_channel_impl_cls class" );
			}

			jmethodID construct = tw_jni_get_method_by_class(env, java_channel_impl_cls, "<init>", "(Ljava/lang/String;Ljava/lang/String;J)V");
			channel = tw_jni_new_object(env, java_channel_impl_cls, construct, nameString, sidString, channelContextHandle);
			LOGD(TAG, "Created Channel Object.");

			jmethodID method = tw_jni_get_method_by_class(env, java_channel_impl_cls, "setListener", "(Lcom/twilio/ipmessaging/ChannelListener;)V");
			LOGD(TAG, "Setting channel listener.");

			env->CallVoidMethod(channel, method, listener);

			//Cleanup
			LOGD(TAG,"createChannelNative: release native string.");
			env->ReleaseStringUTFChars(friendlyName, nativeNameString);


		} else {
			LOGE(TAG,"channels is null");
		}
	}

	return channel;
}

/*
 * Class:     com_twilio_ipmessaging_impl_ChannelsImpl
 * Method:    createChannelNativeWithType
 * Signature: (Ljava/lang/String;Lcom/twilio/ipmessaging/ChannelListener;)Lcom/twilio/ipmessaging/Message;
 */
JNIEXPORT jobject JNICALL Java_com_twilio_ipmessaging_impl_ChannelsImpl_createChannelNativeWithType
(JNIEnv *env, jobject obj, jstring friendlyName, jint type, jobject listener, jlong nativeChannelsContext) {
	jobject channel;
	//jlong nativeChannelsContext = tw_jni_fetch_long(env, obj, "nativeChannelsHandler");
	LOGD(TAG,"createChannelNative : Checking nativeChannelsContext.");
	if (nativeChannelsContext == 0) {
		LOG_W(TAG,"nativeChannelsContext is null");
		return nullptr;
	} else {
		ChannelsContext *channelsContextRecreate = reinterpret_cast<ChannelsContext *>(nativeChannelsContext);
		LOGD(TAG,"client context is recreated.");

		if(channelsContextRecreate == nullptr) {
			LOGW(TAG,"channelsContextRecreate is NULL.");
			return 0;
		}

		if(channelsContextRecreate->channels == nullptr) {
			LOGW(TAG, "createChannelNative : ITChannelsPtr is NULL.");
			return 0;
		}

		ITMChannelsPtr channelsPtr = channelsContextRecreate->channels;

		if (channelsPtr != nullptr) {
			const char *nativeNameString = env->GetStringUTFChars(friendlyName, JNI_FALSE);
			ITMChannelPtr channelPtr = channelsPtr->createChannel();
			if(type == rtd::kTMChannelTypePublic) {
				channelPtr->setType(rtd::kTMChannelTypePublic, [](TMResult result) {LOGD(TAG,"Channel setType to kTMChannelTypePublic command processed");});
			} else {
				channelPtr->setType(rtd::kTMChannelTypePrivate, [](TMResult result) {LOGD(TAG,"Channel setType to kTMChannelTypePrivate command processed");});
			}
			channelPtr->setName(nativeNameString, NULL);
			channelsPtr->add(channelPtr, nullptr);

			//Create channel context
			ChannelContext* channelContext_ = new ChannelContext();
			channelContext_->channel = channelPtr;
			jlong channelContextHandle = reinterpret_cast<jlong>(channelContext_);

			const char* sid = channelPtr->getSid().c_str();
			const char* name = channelPtr->getName().c_str();

			LOGW(TAG,"Channel Name  : %s.", name );
			LOGW(TAG,"Channel Sid %s", sid);


			jstring nameString = env->NewStringUTF(name);
			jstring sidString = env->NewStringUTF(sid);

			//create channel object
			jclass java_channel_impl_cls = tw_jni_find_class(env, "com/twilio/ipmessaging/impl/ChannelImpl");
			if(java_channel_impl_cls != nullptr) {
				LOGD(TAG, "Found java_channel_impl_cls class" );
			}

			jmethodID construct = tw_jni_get_method_by_class(env, java_channel_impl_cls, "<init>", "(Ljava/lang/String;Ljava/lang/String;J)V");
			channel = tw_jni_new_object(env, java_channel_impl_cls, construct, nameString, sidString, channelContextHandle);
			LOGD(TAG, "Created Channel Object.");

			jmethodID method = tw_jni_get_method_by_class(env, java_channel_impl_cls, "setListener", "(Lcom/twilio/ipmessaging/ChannelListener;)V");
			LOGD(TAG, "Setting channel listener.");

			env->CallVoidMethod(channel, method, listener);

			//Cleanup
			LOGD(TAG,"createChannelNative: release native string.");
			env->ReleaseStringUTFChars(friendlyName, nativeNameString);


		} else {
			LOGE(TAG,"channels is null");
		}
	}

	return channel;
}

/*
 * Class:     com_twilio_ipmessaging_impl_ChannelsImpl
 * Method:    getChannelNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT jobject JNICALL Java_com_twilio_ipmessaging_impl_ChannelsImpl_getChannelNative
  (JNIEnv *env, jobject obj, jstring channel_sid, jlong nativeChannelsContext) {

	jobject channel;
	//jlong nativeChannelsContext = tw_jni_fetch_long(env, obj, "nativeChannelsHandler");

	if(channel_sid != nullptr) {
		const char *nativeString = env->GetStringUTFChars(channel_sid, JNI_FALSE);

		LOGD( TAG, "createChannelNative : Checking nativeChannelsContext.");

		if (nativeChannelsContext == 0) {
			LOG_W(TAG, "nativeChannelsContext is null");
			return nullptr;
		} else {

			ChannelsContext *channelsContextRecreate = reinterpret_cast<ChannelsContext *>(nativeChannelsContext);
			LOGD(TAG, "client context is recreated.");

			if(channelsContextRecreate == nullptr) {
				LOG_W(TAG,"createChannelNative : channelsContextRecreate is NULL.");
				return 0;
			}

			if(channelsContextRecreate->channels == nullptr) {
				LOG_W(TAG, "createChannelNative : ITChannelsPtr is NULL.");
				return 0;
			}

			ITMChannelsPtr channelsPtr = channelsContextRecreate->channels;
			if(channelsPtr != nullptr) {
				ITMChannelPtr channelPtr = channelsPtr->getChannel(nativeString);
				if(channelPtr != nullptr) {
					LOGD(TAG, "Creating channel with sid : %s ", nativeString);

					//Create channel context
					ChannelContext* channelContext_ = new ChannelContext();
					channelContext_->channel = channelPtr;
					jlong channelContextHandle = reinterpret_cast<jlong>(channelContext_);

					const char* sid = channelPtr->getSid().c_str();
					const char* name = channelPtr->getName().c_str();

					LOGD(TAG, "Channel Name  : %s.", name );
					LOGD(TAG, "Channel Sid %s", sid);

					jstring nameString = env->NewStringUTF(name);
					jstring sidString = env->NewStringUTF(sid);

					//create channel object
					jclass java_channel_impl_cls = tw_jni_find_class(env, "com/twilio/ipmessaging/impl/ChannelImpl");
					jmethodID construct = tw_jni_get_method_by_class(env, java_channel_impl_cls, "<init>", "(Ljava/lang/String;Ljava/lang/String;J)V");
					channel = tw_jni_new_object(env, java_channel_impl_cls, construct, nameString, sidString, channelContextHandle);
					LOGD(TAG, "Created Channel Object.");

				} else {
					LOGW(TAG, "Java_com_twilio_ipmessaging_impl_ChannelImpl_joinChannel channels is null");
				}
			}
		}
	}
	return channel;
}

/*
 * Class:     com_twilio_ipmessaging_impl_ChannelsImpl
 * Method:    getChannelsNative
 * Signature: (J)[Lcom/twilio/ipmessaging/Channel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_twilio_ipmessaging_impl_ChannelsImpl_getChannelsNative
  (JNIEnv *env, jobject obj, jlong nativeChannelsContext) {

	jobject channel;
	jobjectArray channelsArray ;

	//jlong nativeChannelsContext = tw_jni_fetch_long(env, obj, "nativeChannelsHandler");

	LOGD(TAG, "Checking nativeChannelsContext.");

	if (nativeChannelsContext == 0) {
		LOGW(TAG, "nativeChannelsContext is null");
			return nullptr;
	} else {

		ChannelsContext *channelsContextRecreate = reinterpret_cast<ChannelsContext *>(nativeChannelsContext);
		if(channelsContextRecreate == nullptr) {
			LOGW(TAG, "channelsContextRecreate is null.");
			return 0;
		}

		if(channelsContextRecreate->channels == nullptr) {
			LOGW(TAG, " ITChannelsPtr is null.");
			return 0;
		}

		ITMChannelsPtr channels = channelsContextRecreate->channels;

		std::vector<ITMChannelPtr> publicChannels;
		channels->getPublicChannelsList(publicChannels);
		LOGD(TAG,"public channels count : %d",publicChannels.size());

		jclass java_channel_impl_cls = tw_jni_find_class(env, "com/twilio/ipmessaging/impl/ChannelImpl");

		//jmethodID construct = tw_jni_get_method_by_class(env, java_channel_impl_cls, "<init>", "(Ljava/lang/String;Ljava/lang/String;J)V");
		jmethodID construct = tw_jni_get_method_by_class(env, java_channel_impl_cls, "<init>", "(Ljava/lang/String;Ljava/lang/String;JI)V");
		channelsArray = (jobjectArray) env->NewObjectArray(publicChannels.size(),java_channel_impl_cls, 0);

		for (int i= 0; i<publicChannels.size() ; i++ ) {
			ITMChannelPtr channelPtr = publicChannels[i];
			const char* sid = channelPtr->getSid().c_str();
			const char* name = channelPtr->getName().c_str();
			int status = 0;
			switch (channelPtr->getStatus()) {
				case TMChannelStatus::kTMChannelStatusInvited:
					status = 0;
				case TMChannelStatus::kTMChannelStatusJoined:
					status = 1;
				case TMChannelStatus::kTMChannelStatusNotParticipating:
					status = 2;
				default:
					break;
			}

			ChannelContext* channelContext_ = new ChannelContext();
			channelContext_->channel = channelPtr;
			jlong channelContextHandle = reinterpret_cast<jlong>(channelContext_);
			jstring nameString = env->NewStringUTF(name);
			jstring sidString = env->NewStringUTF(sid);
			channel = tw_jni_new_object(env, java_channel_impl_cls, construct, nameString, sidString, channelContextHandle, status);
			env->SetObjectArrayElement(channelsArray, i, channel);
		}
	}

	return channelsArray ;

}


/*
 * Class:     com_twilio_ipmessaging_impl_ChannelsImpl
 * Method:    getMyChannelsNative
 * Signature: (J)[Lcom/twilio/ipmessaging/Channel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_twilio_ipmessaging_impl_ChannelsImpl_getMyChannelsNative
  (JNIEnv *env, jobject obj, jlong nativeChannelsContext) {

	jobject channel;
	jobjectArray channelsArray ;

	//jlong nativeChannelsContext = tw_jni_fetch_long(env, obj, "nativeChannelsHandler");

	LOGD(TAG, "Checking nativeChannelsContext.");

	if (nativeChannelsContext == 0) {
		LOGW(TAG, "nativeChannelsContext is null");
			return nullptr;
	} else {

		ChannelsContext *channelsContextRecreate = reinterpret_cast<ChannelsContext *>(nativeChannelsContext);
		if(channelsContextRecreate == nullptr) {
			LOGW(TAG, "channelsContextRecreate is null.");
			return 0;
		}

		if(channelsContextRecreate->channels == nullptr) {
			LOGW( TAG, " ITChannelsPtr is null.");
			return 0;
		}

		ITMChannelsPtr channels = channelsContextRecreate->channels;

		std::vector<ITMChannelPtr> channelsList;
		channels->getMyChannelsList(channelsList);

		LOGD(TAG,"my channels count : %d.", channelsList.size() );

		jclass java_channel_impl_cls = tw_jni_find_class(env, "com/twilio/ipmessaging/impl/ChannelImpl");
		jmethodID construct = tw_jni_get_method_by_class(env, java_channel_impl_cls, "<init>", "(Ljava/lang/String;Ljava/lang/String;J)V");
		channelsArray = (jobjectArray) env->NewObjectArray(channelsList.size(),java_channel_impl_cls, 0);

		for (int i= 0; i<channelsList.size() ; i++ ) {
			ITMChannelPtr channelPtr = channelsList[i];
			const char* sid = channelPtr->getSid().c_str();
			const char* name = channelPtr->getName().c_str();

			ChannelContext* channelContext_ = new ChannelContext();
			channelContext_->channel = channelPtr;
			jlong channelContextHandle = reinterpret_cast<jlong>(channelContext_);
			jstring nameString = env->NewStringUTF(name);
			jstring sidString = env->NewStringUTF(sid);
			channel = tw_jni_new_object(env, java_channel_impl_cls, construct, nameString, sidString, channelContextHandle);
			env->SetObjectArrayElement(channelsArray, i, channel);
		}
	}

	return channelsArray ;

}

