/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_ipmessaging_impl_IPMessagingClientImpl_IPMessagingClientListenerInternal */

#ifndef _Included_com_twilio_ipmessaging_impl_IPMessagingClientImpl_IPMessagingClientListenerInternal
#define _Included_com_twilio_ipmessaging_impl_IPMessagingClientImpl_IPMessagingClientListenerInternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_ipmessaging_impl_IPMessagingClientImpl_IPMessagingClientListenerInternal
 * Method:    wrapNativeObserver
 * Signature: (Lcom/twilio/ipmessaging/IPMessagingClientListener;Lcom/twilio/ipmessaging/IPMessagingClient;)J
 */
JNIEXPORT jlong JNICALL Java_com_twilio_ipmessaging_impl_IPMessagingClientImpl_00024IPMessagingClientListenerInternal_wrapNativeObserver
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_twilio_ipmessaging_impl_IPMessagingClientImpl_IPMessagingClientListenerInternal
 * Method:    freeNativeObserver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_twilio_ipmessaging_impl_IPMessagingClientImpl_00024IPMessagingClientListenerInternal_freeNativeObserver
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
