/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_ipmessaging_impl_IPMessagingClientImpl_IPMessagingClientListenerInternal */


class TwilioIPMessagingClientListenerInternalWrapper : public ITMClientListener
{
public:
	TwilioIPMessagingClientListenerInternalWrapper(jobject j_ipmessagingclient_listener, jobject j_ipmessagingclient) {
		j_ipmessagingclient_listener_ = env->NewGlobalRef(j_ipmessagingclient_listener);
		j_ipmessagingclient_ = env->NewGlobalRef(j_ipmessagingclient);
	}

	virtual ~TwilioIPMessagingClientListenerInternalWrapper() {
		if (j_ipmessagingclient_listener_ != NULL) {
			//TODO - we should probably notify jobject that native handle is being destroyed
			env_->DeleteGlobalRef(j_ipmessagingclient_listener_);
			j_ipmessagingclient_listener_ = NULL;
		}
		if (j_ipmessagingclient_ != NULL) {
			env_->DeleteGlobalRef(j_ipmessagingclient_);
			j_ipmessagingclient_ = NULL;
		}

	}
    void setTarget(void* target);

    void onMessage(TMAction action, ITMessagePtr message);
    void onChannel(TMAction action, ITMChannelPtr channel);
    void onMember(TMAction action, ITMMemberPtr member);
    void onError(const std::string& error);

    void onToastNotification(const std::string& channelId, const std::string& messageId);
    void onToastSubscribed();
    void onToastFailed(TNError code);

private:

    jstring stringToJString(JNIEnv * env, const std::string & nativeString) {
            return env->NewStringUTF(nativeString.c_str());
    }
    jobject j_ipmessagingclient_listener_;
    jobject j_ipmessagingclient_;
    void* m_target;
    JNIEnv* env_;
};





/*
 * Class:     com_twilio_ipmessaging_impl_IPMessagingClientImpl_IPMessagingClientListenerInternal
 * Method:    wrapNativeObserver
 * Signature: (Lcom/twilio/ipmessaging/IPMessagingClientListener;Lcom/twilio/ipmessaging/IPMessagingClient;)J
 */
JNIEXPORT jlong JNICALL Java_com_twilio_ipmessaging_impl_IPMessagingClientImpl_00024IPMessagingClientListenerInternal_wrapNativeObserver
  (JNIEnv *env, jobject obj, jobject j_ipMessagingClientListener, jobject j_ipMessagingClientImpl) {
	TwilioIPMessagingClientListenerInternalWrapper ipmsgClientObserverbserver = new TwilioIPMessagingClientListenerInternalWrapper(env, obj, j_ipMessagingClientListener, j_ipMessagingClientImpl);
	return (jlong)ipmsgClientObserverbserver.release();
}

/*
 * Class:     com_twilio_ipmessaging_impl_IPMessagingClientImpl_IPMessagingClientListenerInternal
 * Method:    freeNativeObserver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_twilio_ipmessaging_impl_IPMessagingClientImpl_00024IPMessagingClientListenerInternal_freeNativeObserver
  (JNIEnv *, jobject, jlong) {

}

