/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_ipmessaging_impl_MessageImpl */

#ifndef _Included_com_twilio_ipmessaging_impl_MessageImpl
#define _Included_com_twilio_ipmessaging_impl_MessageImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_ipmessaging_impl_MessageImpl
 * Method:    getChannelSidNative
 * Signature: ()J
 */
JNIEXPORT jstring JNICALL Java_com_twilio_ipmessaging_impl_MessageImpl_getChannelSidNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
