/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_ipmessaging_impl_MembersImpl */

#ifndef _Included_com_twilio_ipmessaging_impl_MembersImpl
#define _Included_com_twilio_ipmessaging_impl_MembersImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_ipmessaging_impl_MembersImpl
 * Method:    getMembersNative
 * Signature: ()[Lcom/twilio/ipmessaging/Member;
 */
JNIEXPORT jobjectArray JNICALL Java_com_twilio_ipmessaging_impl_MembersImpl_getMembersNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
