/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_ipmessaging_impl_MemberImpl */

#ifndef _Included_com_twilio_ipmessaging_impl_MemberImpl
#define _Included_com_twilio_ipmessaging_impl_MemberImpl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
