/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_ipmessaging_impl_TwilioIPMessagingClientImpl_IPMessagingClientListenerInternal */

#ifndef _Included_com_twilio_ipmessaging_impl_TwilioIPMessagingClientImpl_IPMessagingClientListenerInternal
#define _Included_com_twilio_ipmessaging_impl_TwilioIPMessagingClientImpl_IPMessagingClientListenerInternal
#ifdef __cplusplus
extern "C" {
#endif

/*class TwilioIPMessagingClientListenerInternalWrapper : public ITMClientListener
{
public:
	TwilioIPMessagingClientListenerInternalWrapper();
    virtual ~TwilioIPMessagingClientListenerInternalWrapper();

    void onMessage(TMAction action, ITMessagePtr message);
    void onChannel(TMAction action, ITMChannelPtr channel);
    void onMember(TMAction action, ITMMemberPtr member);
    void onError(const std::string& error);

    void onToastNotification(const std::string& channelId, const std::string& messageId);
    void onToastSubscribed();
    void onToastFailed(TNError code);

}; */


/*
 * Class:     com_twilio_ipmessaging_impl_TwilioIPMessagingClientImpl_IPMessagingClientListenerInternal
 * Method:    wrapNativeObserver
 * Signature: (Lcom/twilio/ipmessaging/IPMessagingClientListener;Lcom/twilio/ipmessaging/TwilioIPMessagingClient;)J
 */
JNIEXPORT jlong JNICALL Java_com_twilio_ipmessaging_impl_TwilioIPMessagingClientImpl_00024IPMessagingClientListenerInternal_wrapNativeObserver
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_twilio_ipmessaging_impl_TwilioIPMessagingClientImpl_IPMessagingClientListenerInternal
 * Method:    freeNativeObserver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_twilio_ipmessaging_impl_TwilioIPMessagingClientImpl_00024IPMessagingClientListenerInternal_freeNativeObserver
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
