/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_ipmessaging_impl_MembersImpl */

#ifndef _Included_MembersImpl
#define _Included_MembersImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_ipmessaging_impl_MembersImpl
 * Method:    getMembersNative
 * Signature: ()[Lcom/twilio/ipmessaging/Member;
 */
JNIEXPORT jobjectArray JNICALL Java_com_twilio_ipmessaging_impl_MembersImpl_getMembersNative
  (JNIEnv *, jobject);

/*
 * Class:     com_twilio_ipmessaging_impl_MembersImpl
 * Method:    invite
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_twilio_ipmessaging_impl_MembersImpl_invite
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_twilio_ipmessaging_impl_MembersImpl
 * Method:    add
 * Signature: Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_twilio_ipmessaging_impl_MembersImpl_add
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_twilio_ipmessaging_impl_MembersImpl
 * Method:    remove
 * Signature: (Lcom/twilio/ipmessaging/Member;)V
 */
JNIEXPORT void JNICALL Java_com_twilio_ipmessaging_impl_MembersImpl_remove
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
