/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_TestRTDJNI
#define _Included_TestRTDJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestRTDJNI
 * Method:    testRTD
 * Signature: ()V
 */

JNIEXPORT jlong  JNICALL Java_com_twilio_example_TestRTDJNI_init(JNIEnv *, jobject, jstring);

JNIEXPORT void  JNICALL Java_com_twilio_example_TestRTDJNI_shutDown(JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_com_twilio_example_TestRTDJNI_createMessagingClient(JNIEnv *, jobject, jstring );

JNIEXPORT jobjectArray JNICALL Java_com_twilio_example_TestRTDJNI_getChannelsArray(JNIEnv *, jobject);

JNIEXPORT jobject JNICALL Java_com_twilio_example_TestRTDJNI_getChannels(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_twilio_example_TestRTDJNI_addChannel(JNIEnv *, jobject, jstring );


#ifdef __cplusplus
}
#endif
#endif
