/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_TestRTDJNI
#define _Included_TestRTDJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestRTDJNI
 * Method:    testRTD
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twilio_example_TestRTDJNI_testRTD(JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_com_twilio_example_TestRTDJNI_getMessagingListener(JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_com_twilio_example_TestRTDJNI_getNotificationClient(JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_com_twilio_example_TestRTDJNI_getConfigurationProvider(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
