/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_ipmessaging_impl_TwilioIPMessagingSDKImpl */

#ifndef _Included_com_twilio_ipmessaging_impl_TwilioIPMessagingSDKImpl
#define _Included_com_twilio_ipmessaging_impl_TwilioIPMessagingSDKImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_ipmessaging_impl_TwilioIPMessagingSDKImpl
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twilio_ipmessaging_impl_TwilioIPMessagingSDKImpl_create
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
